In [104]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path
from datetime import datetime

# File to Load
market_data_loading = Path("state_market_tracker.csv")

# Read csv and store into Pandas DataFrames
market_data= pd.read_csv(market_data_loading)
market_data

,period_begin,period_end,period_duration,region_type,region_type_id,table_id,is_seasonally_adjusted,region,city,state,...,sold_above_list_yoy,price_drops,price_drops_mom,price_drops_yoy,off_market_in_two_weeks,off_market_in_two_weeks_mom,off_market_in_two_weeks_yoy,parent_metro_region,parent_metro_region_metro_code,last_updated
0,12/1/2019,12/31/2019,30,state,4,25,f,Hawaii,NaN,Hawaii,...,0.169643,0.065789,-0.015606,-0.033220,0.160000,0.160000,-0.122353,West Region,NaN,2/11/2024 14:26
1,8/1/2012,8/31/2012,30,state,4,6,f,Nebraska,NaN,Nebraska,...,0.033333,NaN,NaN,NaN,0.397306,-0.085452,-0.072391,Midwest Region,NaN,2/11/2024 14:26
2,10/1/2020,10/31/2020,30,state,4,42,f,Virginia,NaN,Virginia,...,0.053852,0.213496,-0.001243,0.013973,0.309778,-0.032221,-0.070342,South Region,NaN,2/11/2024 14:26
3,11/1/2019,11/30/2019,30,state,4,21,f,Georgia,NaN,Georgia,...,-0.000812,0.166690,-0.043263,0.011644,0.275524,-0.005716,0.020963,South Region,NaN,2/11/2024 14:26
4,11/1/2017,11/30/2017,30,state,4,10,f,New Hampshire,NaN,New Hampshire,...,0.062340,0.151584,-0.012595,0.003709,0.083168,-0.088026,-0.002879,Northeast Region,NaN,2/11/2024 14:26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35418,5/1/2016,5/31/2016,30,state,4,22,f,Ohio,NaN,Ohio,...,-0.047351,0.142154,0.013836,0.015876,0.202696,-0.072578,0.024371,Midwest Region,NaN,2/11/2024 14:26
35419,2/1/2016,2/29/2016,30,state,4,50,f,Wyoming,NaN,Wyoming,...,0.021739,NaN,NaN,NaN,0.036648,-0.001932,0.016596,West Region,NaN,2/11/2024 14:26
35420,7/1/2020,7/31/2020,30,state,4,13,f,Connecticut,NaN,Connecticut,...,0.105316,0.101370,-0.013453,-0.052876,0.301511,0.010090,0.137618,Northeast Region,NaN,2/11/2024 14:26
35421,1/1/2021,1/31/2021,30,state,4,24,f,Oregon,NaN,Oregon,...,0.252950,0.176991,0.026794,-0.041832,0.688283,0.061224,0.230851,West Region,NaN,2/11/2024 14:26
35422,3/1/2021,3/31/2021,30,state,4,17,f,Washington D.C.,NaN,Washington D.C.,...,0.045956,0.200533,0.046607,0.028585,0.547958,0.047283,0.052057,South Region,NaN,2/11/2024 14:26

In [108]:
#Dropping Columns in DataFrame that are not needed 
dropped_data= market_data.drop(columns=["period_duration", "region_type", "city", "median_sale_price_mom", "median_sale_price_yoy", "median_list_price_mom", "median_list_price_yoy", 
                  "median_list_ppsf_mom", "median_list_ppsf_yoy", "homes_sold_mom", "homes_sold_yoy", "pending_sales_mom", "pending_sales_yoy", "new_listings_mom", 
                  "new_listings_yoy", "inventory_mom", "inventory_yoy", "months_of_supply_mom", "months_of_supply_yoy", "median_dom_mom", "median_dom_yoy", 
                  "avg_sale_to_list_mom", "avg_sale_to_list_yoy", "avg_sale_to_list_mom", "avg_sale_to_list_yoy", "sold_above_list_mom", "sold_above_list_yoy", 
                  "price_drops", "price_drops_mom", "price_drops_yoy", "off_market_in_two_weeks", "off_market_in_two_weeks_mom", "off_market_in_two_weeks_yoy",
                  "last_updated", "parent_metro_region_metro_code", "is_seasonally_adjusted", "region_type_id", "region", "median_ppsf_mom", "median_ppsf_yoy", "median_dom"])
dropped_data

,period_begin,period_end,table_id,state,state_code,property_type,property_type_id,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,months_of_supply,avg_sale_to_list,sold_above_list,parent_metro_region
0,12/1/2019,12/31/2019,25,Hawaii,HI,Townhouse,13,776200,485000.0,484.0,398.0,16,10.0,10.0,76.0,4.8,1.002073,0.312500,West Region
1,8/1/2012,8/31/2012,6,Nebraska,NE,Multi-Family (2-4 Unit),4,109800,138500.0,56.0,80.0,15,13.0,33.0,125.0,8.3,0.916258,0.133333,Midwest Region
2,10/1/2020,10/31/2020,42,Virginia,VA,Condo/Co-op,3,275700,440600.0,264.0,258.0,1256,1140.0,1521.0,2712.0,2.2,0.994101,0.308121,South Region
3,11/1/2019,11/30/2019,21,Georgia,GA,All Residential,-1,237100,254800.0,117.0,125.0,11366,9352.0,12986.0,50603.0,4.5,0.976470,0.178075,South Region
4,11/1/2017,11/30/2017,10,New Hampshire,NH,Townhouse,13,200000,262300.0,135.0,148.0,173,141.0,105.0,442.0,2.6,0.981605,0.277457,Northeast Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35418,5/1/2016,5/31/2016,22,Ohio,OH,Multi-Family (2-4 Unit),4,77200,137000.0,38.0,88.0,299,221.0,459.0,1829.0,6.1,0.926174,0.090301,Midwest Region
35419,2/1/2016,2/29/2016,50,Wyoming,WY,Single Family Residential,6,273000,296600.0,130.0,138.0,138,59.0,197.0,940.0,6.8,0.973945,0.021739,West Region
35420,7/1/2020,7/31/2020,13,Connecticut,CT,Multi-Family (2-4 Unit),4,236300,324500.0,98.0,172.0,226,236.0,485.0,1095.0,4.8,0.995301,0.411504,Northeast Region
35421,1/1/2021,1/31/2021,24,Oregon,OR,Townhouse,13,373000,460900.0,239.0,261.0,187,255.0,263.0,226.0,1.2,1.007853,0.465241,West Region
35422,3/1/2021,3/31/2021,17,Washington D.C.,DC,All Residential,-1,635000,641000.0,545.0,552.0,1022,1053.0,1288.0,1875.0,1.8,1.013034,0.419765,South Region

In [109]:
#Splitting columns for period beginning
def convert(datetime_string_pb): 
    datetime_str= datetime.strptime(datetime_string_pb, "%m/%d/%Y")

    return datetime_str

pb_series = pd.Series(dropped_data["period_begin"])

year_array= []
month_array = []

for each in pb_series:
    pb_convert = convert(each)
    year_array.append(pb_convert.year)
    month_array.append(pb_convert.month)
    
dropped_data["year"]= year_array
dropped_data["month"] = month_array

market_data_updated= dropped_data.drop(columns=["period_begin", "period_end"])
market_data_updated

,table_id,state,state_code,property_type,property_type_id,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,months_of_supply,avg_sale_to_list,sold_above_list,parent_metro_region,year,month
0,25,Hawaii,HI,Townhouse,13,776200,485000.0,484.0,398.0,16,10.0,10.0,76.0,4.8,1.002073,0.312500,West Region,2019,12
1,6,Nebraska,NE,Multi-Family (2-4 Unit),4,109800,138500.0,56.0,80.0,15,13.0,33.0,125.0,8.3,0.916258,0.133333,Midwest Region,2012,8
2,42,Virginia,VA,Condo/Co-op,3,275700,440600.0,264.0,258.0,1256,1140.0,1521.0,2712.0,2.2,0.994101,0.308121,South Region,2020,10
3,21,Georgia,GA,All Residential,-1,237100,254800.0,117.0,125.0,11366,9352.0,12986.0,50603.0,4.5,0.976470,0.178075,South Region,2019,11
4,10,New Hampshire,NH,Townhouse,13,200000,262300.0,135.0,148.0,173,141.0,105.0,442.0,2.6,0.981605,0.277457,Northeast Region,2017,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35418,22,Ohio,OH,Multi-Family (2-4 Unit),4,77200,137000.0,38.0,88.0,299,221.0,459.0,1829.0,6.1,0.926174,0.090301,Midwest Region,2016,5
35419,50,Wyoming,WY,Single Family Residential,6,273000,296600.0,130.0,138.0,138,59.0,197.0,940.0,6.8,0.973945,0.021739,West Region,2016,2
35420,13,Connecticut,CT,Multi-Family (2-4 Unit),4,236300,324500.0,98.0,172.0,226,236.0,485.0,1095.0,4.8,0.995301,0.411504,Northeast Region,2020,7
35421,24,Oregon,OR,Townhouse,13,373000,460900.0,239.0,261.0,187,255.0,263.0,226.0,1.2,1.007853,0.465241,West Region,2021,1
35422,17,Washington D.C.,DC,All Residential,-1,635000,641000.0,545.0,552.0,1022,1053.0,1288.0,1875.0,1.8,1.013034,0.419765,South Region,2021,3

In [110]:
#writing updated DataFrame to updated csv 
market_data_updated.to_csv("cleaned_state_market_tracker.csv")