In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import distutils as _distutils
import tensorflow as tf
import tensorflow.compat.v1 as tf
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

C:\Users\tamar\AppData\Local\Temp\ipykernel_42900\884216736.py:5: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Import and read the cleaned_state_market_tracker.csv.
import pandas as pd 
market_df = pd.read_csv("../Resources/cleaned_state_market_tracker.csv")
market_df.head()

,Unnamed: 0,table_id,state,state_code,property_type,property_type_id,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,months_of_supply,avg_sale_to_list,sold_above_list,parent_metro_region,year,month
0,0,25,Hawaii,HI,Townhouse,13,776200,485000.0,484.0,398.0,16,10.0,10.0,76.0,4.8,1.002073,0.312500,West Region,2019,12
1,1,6,Nebraska,NE,Multi-Family (2-4 Unit),4,109800,138500.0,56.0,80.0,15,13.0,33.0,125.0,8.3,0.916258,0.133333,Midwest Region,2012,8
2,2,42,Virginia,VA,Condo/Co-op,3,275700,440600.0,264.0,258.0,1256,1140.0,1521.0,2712.0,2.2,0.994101,0.308121,South Region,2020,10
3,3,21,Georgia,GA,All Residential,-1,237100,254800.0,117.0,125.0,11366,9352.0,12986.0,50603.0,4.5,0.976470,0.178075,South Region,2019,11
4,4,10,New Hampshire,NH,Townhouse,13,200000,262300.0,135.0,148.0,173,141.0,105.0,442.0,2.6,0.981605,0.277457,Northeast Region,2017,11

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
market_df.drop(columns = ['table_id','property_type_id', 'state_code', 'median_ppsf', "median_list_ppsf", "sold_above_list", "year", "months_of_supply", "state", "parent_metro_region"], inplace=True)
market_df

,Unnamed: 0,property_type,median_sale_price,median_list_price,homes_sold,pending_sales,new_listings,inventory,avg_sale_to_list,month
0,0,Townhouse,776200,485000.0,16,10.0,10.0,76.0,1.002073,12
1,1,Multi-Family (2-4 Unit),109800,138500.0,15,13.0,33.0,125.0,0.916258,8
2,2,Condo/Co-op,275700,440600.0,1256,1140.0,1521.0,2712.0,0.994101,10
3,3,All Residential,237100,254800.0,11366,9352.0,12986.0,50603.0,0.976470,11
4,4,Townhouse,200000,262300.0,173,141.0,105.0,442.0,0.981605,11
...,...,...,...,...,...,...,...,...,...,...
35418,35418,Multi-Family (2-4 Unit),77200,137000.0,299,221.0,459.0,1829.0,0.926174,5
35419,35419,Single Family Residential,273000,296600.0,138,59.0,197.0,940.0,0.973945,2
35420,35420,Multi-Family (2-4 Unit),236300,324500.0,226,236.0,485.0,1095.0,0.995301,7
35421,35421,Townhouse,373000,460900.0,187,255.0,263.0,226.0,1.007853,1
35422,35422,All Residential,635000,641000.0,1022,1053.0,1288.0,1875.0,1.013034,3

In [4]:
null_market_df = market_df.dropna(how='any', axis= 0)
null_market_df

,Unnamed: 0,property_type,median_sale_price,median_list_price,homes_sold,pending_sales,new_listings,inventory,avg_sale_to_list,month
0,0,Townhouse,776200,485000.0,16,10.0,10.0,76.0,1.002073,12
1,1,Multi-Family (2-4 Unit),109800,138500.0,15,13.0,33.0,125.0,0.916258,8
2,2,Condo/Co-op,275700,440600.0,1256,1140.0,1521.0,2712.0,0.994101,10
3,3,All Residential,237100,254800.0,11366,9352.0,12986.0,50603.0,0.976470,11
4,4,Townhouse,200000,262300.0,173,141.0,105.0,442.0,0.981605,11
...,...,...,...,...,...,...,...,...,...,...
35418,35418,Multi-Family (2-4 Unit),77200,137000.0,299,221.0,459.0,1829.0,0.926174,5
35419,35419,Single Family Residential,273000,296600.0,138,59.0,197.0,940.0,0.973945,2
35420,35420,Multi-Family (2-4 Unit),236300,324500.0,226,236.0,485.0,1095.0,0.995301,7
35421,35421,Townhouse,373000,460900.0,187,255.0,263.0,226.0,1.007853,1
35422,35422,All Residential,635000,641000.0,1022,1053.0,1288.0,1875.0,1.013034,3

In [5]:
# Determine the number of unique values in each column.
category_values = null_market_df.nunique()
category_values

Unnamed: 0           34012
property_type            5
median_sale_price     6061
median_list_price     5553
homes_sold            8834
pending_sales         7719
new_listings          9472
inventory            14159
avg_sale_to_list     33875
month                   12
dtype: int64

In [6]:
# Split our preprocessed data into our features and target arrays
y = null_market_df["property_type"].astype('category').cat.codes
X = null_market_df.drop(["property_type"], axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=55)
y

0        4
1        2
2        1
3        0
4        4
        ..
35418    2
35419    3
35420    2
35421    4
35422    0
Length: 34012, dtype: int8

In [7]:
# Create a StandardScaler instances
scaler = MinMaxScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])

nn_model = tf.keras.models.Sequential()

hidden_nodes_layer1 = 4
hidden_nodes_layer2 = 4
hidden_nodes_layer3= 1 

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation= "sigmoid"))

# Check the structure of the model
nn_model.summary()

print(number_input_features)

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 65 (260.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

9

In [9]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [10]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train, epochs=50)

Epoch 1/50

798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 917us/step - accuracy: 0.1965 - loss: -4.2414
Epoch 2/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2021 - loss: -86.3857
Epoch 3/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.2024 - loss: -408.4139
Epoch 4/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 0.1998 - loss: -1032.8676
Epoch 5/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 888us/step - accuracy: 0.1968 - loss: -2022.2113
Epoch 6/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 862us/step - accuracy: 0.2039 - loss: -3386.8010
Epoch 7/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 844us/step - accuracy: 0.1978 - loss: -5266.1587
Epoch 8/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2032 - loss: -7404.5439
Epoch 9/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 924us/step - accuracy: 0.1968 - loss: -10243.7100
Epoch 10/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.2000 - loss: -13524.8623
Epoch 11/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2000 - loss: -17249.6113
Epoch 12/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2015 - loss: -21548.4043
Epoch 13/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1953 - loss: -26749.6680
Epoch 14/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2018 - loss: -32420.7207
Epoch 15/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2023 - loss: -38500.9258
Epoch 16/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1958 - loss: -46339.8086
Epoch 17/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1989 - loss: -53541.6016
Epoch 18/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2003 - loss: -62467.0742
Epoch 19/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2042 - loss: -72440.2266
Epoch 20/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1959 - loss: -81688.3203
Epoch 21/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1986 - loss: -94010.4297
Epoch 22/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1982 - loss: -106567.7188
Epoch 23/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2026 - loss: -118152.0234
Epoch 24/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2054 - loss: -132529.4688
Epoch 25/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2027 - loss: -148770.2500
Epoch 26/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1998 - loss: -164923.8594
Epoch 27/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2019 - loss: -179947.6094
Epoch 28/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2013 - loss: -197060.2500
Epoch 29/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2015 - loss: -223637.8750
Epoch 30/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2003 - loss: -240721.6562
Epoch 31/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2018 - loss: -259067.1875
Epoch 32/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2022 - loss: -283946.1875
Epoch 33/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1988 - loss: -313006.9688
Epoch 34/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.1999 - loss: -337110.3438
Epoch 35/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2001 - loss: -363872.1562
Epoch 36/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2011 - loss: -388517.7188
Epoch 37/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2049 - loss: -418261.3438
Epoch 38/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1998 - loss: -445899.9688
Epoch 39/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2005 - loss: -481938.4688
Epoch 40/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2002 - loss: -520494.7812
Epoch 41/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1995 - loss: -557691.3750
Epoch 42/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2009 - loss: -598008.2500
Epoch 43/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2049 - loss: -624768.2500
Epoch 44/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2020 - loss: -666604.0000
Epoch 45/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2018 - loss: -703530.0000
Epoch 46/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2004 - loss: -759928.8125
Epoch 47/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2007 - loss: -806193.0000
Epoch 48/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2018 - loss: -847118.6875
Epoch 49/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1970 - loss: -909275.8750
Epoch 50/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1995 - loss: -958421.9375

In [11]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

266/266 - 1s - 3ms/step - accuracy: 0.2004 - loss: -9.9490e+05
Loss: -994902.4375, Accuracy: 0.20039986073970795