In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import distutils as _distutils
import tensorflow as tf
import tensorflow.compat.v1 as tf
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

C:\Users\tamar\AppData\Local\Temp\ipykernel_43592\884216736.py:5: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# Import and read the cleaned_state_market_tracker.csv.
import pandas as pd 
market_df = pd.read_csv("cleaned_state_market_tracker.csv")
market_df.head()

,table_id,state,state_code,property_type,property_type_id,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,months_of_supply,avg_sale_to_list,sold_above_list,parent_metro_region,year,month,rei_id
0,1,Alabama,AL,Multi-Family (2-4 Unit),4,61900,179000.0,27.0,95.0,4,3.0,3.0,15.0,3.8,0.900837,0.000000,South Region,2014,3,1
1,1,Alabama,AL,Condo/Co-op,3,363000,353700.0,388.0,185.0,281,230.0,286.0,902.0,3.2,0.983281,0.135231,South Region,2023,7,2
2,1,Alabama,AL,Townhouse,13,130500,186400.0,83.0,95.0,116,61.0,120.0,430.0,3.7,0.962387,0.120690,South Region,2015,4,3
3,1,Alabama,AL,All Residential,-1,191000,192400.0,97.0,98.0,5181,3033.0,5544.0,20941.0,4.0,0.971602,0.182397,South Region,2017,6,4
4,1,Alabama,AL,Single Family Residential,6,138400,162100.0,72.0,86.0,2042,724.0,2815.0,13234.0,6.5,0.950388,0.154750,South Region,2013,2,5

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
market_df.drop(columns = ['table_id','property_type_id', 'state_code', 'median_ppsf', "median_list_ppsf", "sold_above_list", "year", "months_of_supply", "state", "parent_metro_region"], inplace=True)
market_df

,property_type,median_sale_price,median_list_price,homes_sold,pending_sales,new_listings,inventory,avg_sale_to_list,month,rei_id
0,Multi-Family (2-4 Unit),61900,179000.0,4,3.0,3.0,15.0,0.900837,3,1
1,Condo/Co-op,363000,353700.0,281,230.0,286.0,902.0,0.983281,7,2
2,Townhouse,130500,186400.0,116,61.0,120.0,430.0,0.962387,4,3
3,All Residential,191000,192400.0,5181,3033.0,5544.0,20941.0,0.971602,6,4
4,Single Family Residential,138400,162100.0,2042,724.0,2815.0,13234.0,0.950388,2,5
...,...,...,...,...,...,...,...,...,...,...
35418,Multi-Family (2-4 Unit),153500,244900.0,9,8.0,14.0,33.0,0.947979,10,35419
35419,Multi-Family (2-4 Unit),141600,231700.0,5,9.0,12.0,33.0,0.941061,5,35420
35420,Single Family Residential,243700,249200.0,1509,1505.0,1928.0,4627.0,0.977123,4,35421
35421,Townhouse,73800,143500.0,19,6.0,15.0,99.0,0.944210,10,35422
35422,Condo/Co-op,157700,153100.0,24,5.0,32.0,222.0,0.915664,7,35423

In [4]:
null_market_df = market_df.dropna(how='any', axis= 0)
null_market_df

,property_type,median_sale_price,median_list_price,homes_sold,pending_sales,new_listings,inventory,avg_sale_to_list,month,rei_id
0,Multi-Family (2-4 Unit),61900,179000.0,4,3.0,3.0,15.0,0.900837,3,1
1,Condo/Co-op,363000,353700.0,281,230.0,286.0,902.0,0.983281,7,2
2,Townhouse,130500,186400.0,116,61.0,120.0,430.0,0.962387,4,3
3,All Residential,191000,192400.0,5181,3033.0,5544.0,20941.0,0.971602,6,4
4,Single Family Residential,138400,162100.0,2042,724.0,2815.0,13234.0,0.950388,2,5
...,...,...,...,...,...,...,...,...,...,...
35418,Multi-Family (2-4 Unit),153500,244900.0,9,8.0,14.0,33.0,0.947979,10,35419
35419,Multi-Family (2-4 Unit),141600,231700.0,5,9.0,12.0,33.0,0.941061,5,35420
35420,Single Family Residential,243700,249200.0,1509,1505.0,1928.0,4627.0,0.977123,4,35421
35421,Townhouse,73800,143500.0,19,6.0,15.0,99.0,0.944210,10,35422
35422,Condo/Co-op,157700,153100.0,24,5.0,32.0,222.0,0.915664,7,35423

In [5]:
# Determine the number of unique values in each column.
category_values = null_market_df.nunique()
category_values

property_type            5
median_sale_price     6061
median_list_price     5553
homes_sold            8834
pending_sales         7719
new_listings          9472
inventory            14159
avg_sale_to_list     33875
month                   12
rei_id               34012
dtype: int64

In [6]:
# Split our preprocessed data into our features and target arrays
y = null_market_df["property_type"].astype('category').cat.codes
X = null_market_df.drop(["property_type"], axis=1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=55)
y

0        2
1        1
2        4
3        0
4        3
        ..
35418    2
35419    2
35420    3
35421    4
35422    1
Length: 34012, dtype: int8

In [7]:
# Create a StandardScaler instances
scaler = MinMaxScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [8]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])

nn_model = tf.keras.models.Sequential()

hidden_nodes_layer1 = 4
hidden_nodes_layer2 = 4
hidden_nodes_layer3= 1 

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='sigmoid'))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='sigmoid'))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation= "sigmoid"))

# Check the structure of the model
nn_model.summary()

print(number_input_features)

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 65 (260.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

9

In [9]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [10]:
# Train the model
fit_model = nn_model.fit(X_train_scaled,y_train, epochs=50)

Epoch 1/50

798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 854us/step - accuracy: 0.2044 - loss: 0.1489
Epoch 2/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.1968 - loss: -3.8418
Epoch 3/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.1992 - loss: -8.0370
Epoch 4/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 864us/step - accuracy: 0.1964 - loss: -11.9461
Epoch 5/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1967 - loss: -15.8046
Epoch 6/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1989 - loss: -19.3694
Epoch 7/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - accuracy: 0.1958 - loss: -22.9364
Epoch 8/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 902us/step - accuracy: 0.1972 - loss: -26.4234
Epoch 9/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1931 - loss: -30.6570
Epoch 10/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1957 - loss: -34.2728
Epoch 11/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2021 - loss: -37.5312
Epoch 12/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 889us/step - accuracy: 0.1981 - loss: -41.7892
Epoch 13/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 978us/step - accuracy: 0.1940 - loss: -45.1771
Epoch 14/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1983 - loss: -48.6420
Epoch 15/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2004 - loss: -52.9097
Epoch 16/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1920 - loss: -56.7114
Epoch 17/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 966us/step - accuracy: 0.2007 - loss: -59.3055
Epoch 18/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 953us/step - accuracy: 0.1993 - loss: -64.4934
Epoch 19/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1971 - loss: -67.6291
Epoch 20/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.2036 - loss: -70.1142
Epoch 21/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 967us/step - accuracy: 0.2027 - loss: -74.5334
Epoch 22/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2033 - loss: -77.4256
Epoch 23/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 821us/step - accuracy: 0.2004 - loss: -82.3352
Epoch 24/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.1978 - loss: -85.1339
Epoch 25/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.1999 - loss: -88.8292
Epoch 26/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.1985 - loss: -91.6266
Epoch 27/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - accuracy: 0.1993 - loss: -95.8712
Epoch 28/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 762us/step - accuracy: 0.1944 - loss: -102.2988
Epoch 29/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.1950 - loss: -105.0484
Epoch 30/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 772us/step - accuracy: 0.1945 - loss: -109.1888
Epoch 31/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 778us/step - accuracy: 0.1989 - loss: -111.0095
Epoch 32/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 966us/step - accuracy: 0.2027 - loss: -114.5701
Epoch 33/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 724us/step - accuracy: 0.1999 - loss: -118.2252
Epoch 34/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 749us/step - accuracy: 0.1972 - loss: -123.0715
Epoch 35/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.1974 - loss: -127.3783
Epoch 36/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - accuracy: 0.2041 - loss: -128.7249
Epoch 37/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.2027 - loss: -134.4462
Epoch 38/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 781us/step - accuracy: 0.2010 - loss: -137.5661
Epoch 39/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 837us/step - accuracy: 0.1991 - loss: -139.5304
Epoch 40/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 827us/step - accuracy: 0.2002 - loss: -142.5081
Epoch 41/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.2014 - loss: -149.2832
Epoch 42/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2009 - loss: -150.6967
Epoch 43/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.2036 - loss: -154.3235
Epoch 44/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1975 - loss: -158.7880
Epoch 45/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2011 - loss: -161.1457
Epoch 46/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2009 - loss: -163.8323
Epoch 47/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 984us/step - accuracy: 0.2007 - loss: -169.1371
Epoch 48/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.2010 - loss: -170.6914
Epoch 49/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1971 - loss: -178.4836
Epoch 50/50
798/798 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1997 - loss: -179.3385

In [11]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

266/266 - 0s - 1ms/step - accuracy: 0.2019 - loss: -1.7904e+02
Loss: -179.04246520996094, Accuracy: 0.2019287347793579